version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: contacts_db
    environment:
      POSTGRES_USER: ${DB_USER:-contactuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-contactpass}
      POSTGRES_DB: ${DB_NAME:-contacts_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-contactuser} -d ${DB_NAME:-contacts_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: contacts_api
    environment:
      DATABASE: postgresql://${DB_USER:-contactuser}:${DB_PASSWORD:-contactpass}@db:5432/${DB_NAME:-contacts_db}
      PORT: 80
      ENVIRONMENT: ${ENVIRONMENT:-development}
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/root/migrations
      - ./seed:/root/seed
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
